### ISSUE TITLE
Convert from schema to function

### ISSUE THREAD

**Issue by siliconlad** [cadifyai/tool2schema#48]
It would be nice to have the ability to take a schema (e.g. returned by OpenAI) and return a function that can be called that executes the function with the appropriate parameters.

For example:

```python
import tool2schema
import tools  # Module containing all tools

f = tool2schema.ParseSchema(tools, schema)
f()  # Call the function
```

Would be nice if it did automatic validation to check if the schema conforms with the function definition (perhaps using Pydantic?). It should use the function name to match the schema to the appropriate function.

Given we are supporting OpenAI only at the moment, the `schema` variable is a subset of the [Chat Completion object](https://platform.openai.com/docs/api-reference/chat/object). That is:

```python
schema = {
  "function": {
    "name": "my_function",
    "arguments": # JSON string of arguments
  }
}
```

I suppose this is `schema2tool` and we've already outgrown our `tool2schema` name!

**Comment by siliconlad** [comment]
Thoughts @lorenzocelli?

**Comment by lorenzocelli** [comment]
Yep looks like a useful tool!

In this example:
```
f = tool2schema.ParseSchema(tools, schema)
f()  # Call the function
```

Could `f` be a wrapper to one of the decorated functions, without passing any tools?

**Comment by siliconlad** [comment]
How would not passing `tools` work? I added that because you would need to get the function somehow.

`schema` being the JSON object that is returned by the OpenAI API so has no reference to things like `FunctionSchema`.

**Comment by siliconlad** [comment]
Let's try it without a wrapper for now (keeps the one liner shorter).

The wrapper could potentially be useful later on, so let's keep that in mind!
